# fly.toml app configuration file generated for chain-subconverter-7yy7jg on 2025-08-02T03:41:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chain-subconverter-7yy7jg'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
